name: All Tests

on:
  schedule:
    # Runs every Monday at 12:00 UTC
    - cron: '0 12 * * 1'
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Install GROMACS
      run: |
        sudo apt-get update
        sudo apt-get install -y gromacs

    - name: setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        check-latest: true

    - run: python -m pip install tox coverage[toml]

    - name: run Python tests
      run: |
        tox -e tests-all
        
    - name: generate coverage.xml
      run: coverage xml

    - name: upload to codecov.io
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        files: tests/coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
